"""Shared PDF helpers used by the per-game batch exporters."""
from datetime import date

from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch

MARGIN_BOTTOM = 0.75 * inch


def draw_cover_page(c, title: str, count: int):
    width, height = letter
    c.setFont("Helvetica-Bold", 28)
    c.drawCentredString(width / 2, height / 2 + 0.4 * inch, title)

    c.setFont("Helvetica", 14)
    c.setFillColorRGB(0.35, 0.35, 0.35)
    label = f"{count} puzzle" + ("s" if count != 1 else "")
    c.drawCentredString(width / 2, height / 2 - 0.1 * inch, label)

    c.setFont("Helvetica", 10)
    c.drawCentredString(width / 2, MARGIN_BOTTOM, f"Generated by Puzzle Forge — {date.today():%B %d, %Y}")
    c.setFillColorRGB(0, 0, 0)
    c.showPage()
