"""Shared PDF helpers used by the per-game batch exporters."""
from datetime import date

from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch

MARGIN_BOTTOM = 0.75 * inch
TITLE_FONT = "Helvetica-Bold"


def _wrap_title(c, title: str, font_size: int, max_width: float) -> list[str]:
    words = title.split()
    lines = []
    current = ""
    for word in words:
        trial = f"{current} {word}".strip()
        if not current or c.stringWidth(trial, TITLE_FONT, font_size) <= max_width:
            current = trial
        else:
            lines.append(current)
            current = word
    if current:
        lines.append(current)
    return lines


def draw_cover_page(c, title: str, count: int, show_credit: bool = True):
    width, height = letter
    max_width = width - 1.5 * inch

    font_size = 28
    lines = _wrap_title(c, title, font_size, max_width)
    while len(lines) > 2 and font_size > 16:
        font_size -= 2
        lines = _wrap_title(c, title, font_size, max_width)

    c.setFont(TITLE_FONT, font_size)
    line_gap = font_size * 1.2
    top_y = height / 2 + 0.4 * inch + (len(lines) - 1) * line_gap / 2
    for i, line in enumerate(lines):
        c.drawCentredString(width / 2, top_y - i * line_gap, line)

    c.setFont("Helvetica", 14)
    c.setFillColorRGB(0.35, 0.35, 0.35)
    label = f"{count} puzzle" + ("s" if count != 1 else "")
    c.drawCentredString(width / 2, height / 2 - 0.1 * inch - (len(lines) - 1) * line_gap / 2, label)

    if show_credit:
        c.setFont("Helvetica", 10)
        c.drawCentredString(width / 2, MARGIN_BOTTOM, f"Generated by Puzzle Forge — {date.today():%B %d, %Y}")
    c.setFillColorRGB(0, 0, 0)
    c.showPage()
