"""Add Puzzle model

Revision ID: 1cd8cf5e4b17
Revises: 
Create Date: 2026-08-16 21:27:17.886555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cd8cf5e4b17'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('puzzle',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('game_type', sa.String(length=32), nullable=False),
    sa.Column('theme', sa.String(length=200), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('puzzle')
    # ### end Alembic commands ###
