"""Add prefer_offline_wordbank to user

Revision ID: bdca70ffdf13
Revises: 501f29dcb798
Create Date: 2026-09-02 19:28:23.536476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdca70ffdf13'
down_revision = '501f29dcb798'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prefer_offline_wordbank', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('prefer_offline_wordbank')

    # ### end Alembic commands ###
